name = "lowkey-panel"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# ===== D1 Database: Lowkeybottt =====
[[d1_databases]]
binding = "DB"
database_name = "Lowkeybottt"
database_id = "b4e53037-38b1-49d7-bfdf-27f16b2a31be"
